// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixtjeocobjqcqladeaqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4dGplb2NvYmpxY3FsYWRlYXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1MzMzMDcsImV4cCI6MjA1MzEwOTMwN30.laNiOkD0hLHLcZZx1nlmc2zW1nTWWCx7O-P7SkjamwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);